name: Tests

on: [push]

jobs:
  test:

    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [8, 10, 12]

    steps:
    - uses: actions/checkout@v1
    - name: Setup
      uses: actions/setup-node@v1
      with:
        node-version: ${{ matrix.node-version }}
    - name: Run tests
      run: |
        npm install
        npm run build
        npm test
      env:
        CI: true
